# app/routes/setup.py
"""
First-run setup wizard for Emi SQLite
"""
from flask import Blueprint, render_template, request, jsonify, session, redirect, url_for
from pathlib import Path
import json
import uuid
from datetime import datetime

from app.models.base import get_session
from app.assistant.entity_management.entity_cards import EntityCard

setup_bp = Blueprint('setup', __name__)

def is_setup_complete():
    """Check if initial setup has been completed"""
    resources_dir = Path(__file__).resolve().parents[2] / 'resources'
    user_data_file = resources_dir / 'resource_user_data.json'
    return user_data_file.exists()

def get_setup_status():
    """Get detailed setup status"""
    resources_dir = Path(__file__).resolve().parents[2] / 'resources'
    return {
        'resource_user_data': (resources_dir / 'resource_user_data.json').exists(),
        'resource_assistant_personality': (resources_dir / 'resource_assistant_personality_data.json').exists(),
        'resource_relationship_config': (resources_dir / 'resource_relationship_config.json').exists(),
        'resource_chat_guidelines': (resources_dir / 'resource_chat_guidelines_data.json').exists(),
    }

@setup_bp.route('/setup', methods=['GET'])
def setup_wizard():
    """Render the setup wizard"""
    if is_setup_complete():
        # Setup already done, redirect to chat
        return redirect(url_for('chat_bot.chat_bot'))
    
    return render_template('setup_wizard.html')

@setup_bp.route('/api/setup/status', methods=['GET'])
def setup_status():
    """Get setup status"""
    return jsonify({
        'complete': is_setup_complete(),
        'details': get_setup_status()
    })

@setup_bp.route('/api/setup/complete', methods=['POST'])
def complete_setup():
    """Complete the setup process"""
    try:
        data = request.json
        
        # Validate required fields
        if not data.get('first_name') or not data.get('last_name'):
            return jsonify({'success': False, 'error': 'First and last name are required'}), 400
        if not data.get('pronouns'):
            return jsonify({'success': False, 'error': 'Pronouns are required'}), 400
        if not data.get('assistant_name'):
            return jsonify({'success': False, 'error': 'Assistant name is required'}), 400
        if not data.get('relationship_type'):
            return jsonify({'success': False, 'error': 'Relationship type is required'}), 400
        if not data.get('openai_api_key'):
            return jsonify({'success': False, 'error': 'OpenAI API key is required'}), 400
        if not data.get('timezone'):
            return jsonify({'success': False, 'error': 'Timezone is required'}), 400
        
        # Create resources directory if it doesn't exist
        resources_dir = Path(__file__).resolve().parents[2] / 'resources'
        resources_dir.mkdir(exist_ok=True)
        
        # 0. Save API key and settings to .env file
        project_root = Path(__file__).resolve().parents[2]
        env_file = project_root / '.env'
        
        # Read existing .env if it exists
        env_content = {}
        if env_file.exists():
            with open(env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        env_content[key.strip()] = value.strip()
        
        # Update with new values
        env_content['OPENAI_API_KEY'] = data['openai_api_key']
        env_content['TIMEZONE'] = data['timezone']
        
        # Write back to .env
        with open(env_file, 'w') as f:
            f.write("# Emi Configuration\n")
            f.write("# Generated by setup wizard\n\n")
            f.write("# Core Settings\n")
            f.write(f"OPENAI_API_KEY={env_content.get('OPENAI_API_KEY', '')}\n")
            f.write(f"TIMEZONE={env_content.get('TIMEZONE', '')}\n\n")
            
            # Write any other existing keys
            for key, value in env_content.items():
                if key not in ['OPENAI_API_KEY', 'TIMEZONE']:
                    f.write(f"{key}={value}\n")
        
        # 1. Create user_data.json
        # Split pronouns into subjective/objective (e.g., "he/him" -> "he", "him")
        pronouns = data['pronouns'].split('/')
        pronoun_subjective = pronouns[0] if len(pronouns) > 0 else data['pronouns']
        pronoun_objective = pronouns[1] if len(pronouns) > 1 else pronouns[0]
        
        user_data = {
            'first_name': data['first_name'],
            'middle_name': data.get('middle_name'),
            'last_name': data['last_name'],
            'preferred_name': data.get('preferred_name'),
            'full_name': data['full_name'],
            'pronouns': {
                'subjective': pronoun_subjective,
                'objective': pronoun_objective
            }
        }
        
        # Add optional fields
        if data.get('birthdate'):
            user_data['birthdate'] = data['birthdate']
        
        if data.get('job'):
            user_data['job'] = data['job']
        
        # Add important people
        important_people = data.get('important_people', [])
        if important_people:
            user_data['important_people'] = important_people
        
        # Add additional context
        if data.get('additional_context'):
            user_data['additional_context'] = data['additional_context']
        
        with open(resources_dir / 'resource_user_data.json', 'w') as f:
            json.dump(user_data, f, indent=2)
        
        # 2. Create resource_assistant_personality.json
        assistant_personality = {
            'name': data['assistant_name']
        }
        
        if data.get('assistant_personality'):
            assistant_personality['personality'] = data['assistant_personality']
        
        if data.get('assistant_backstory'):
            assistant_personality['backstory'] = data['assistant_backstory']
        
        with open(resources_dir / 'resource_assistant_personality_data.json', 'w') as f:
            json.dump(assistant_personality, f, indent=2)
        
        # 3. Create resource_relationship_config.json
        relationship_config = {
            'type': data['relationship_type'],
            'description': data.get('relationship_description', ''),
            'role': data.get('assistant_role', '')
        }
        
        with open(resources_dir / 'resource_relationship_config.json', 'w') as f:
            json.dump(relationship_config, f, indent=2)
        
        # 4. Create resource_chat_guidelines.json
        chat_guidelines = {
            'style': data.get('communication_style', 'direct'),
            'guidelines': data.get('chat_guidelines', '')
        }
        
        with open(resources_dir / 'resource_chat_guidelines_data.json', 'w') as f:
            json.dump(chat_guidelines, f, indent=2)
        
        # 5. Create initial entity cards for important people (SQLite version)
        session_db = get_session()
        try:
            full_name = user_data['full_name']
            
            # Delete existing entity cards to avoid duplicates
            existing_cards = session_db.query(EntityCard).all()
            for card in existing_cards:
                session_db.delete(card)
            session_db.commit()
            
            # Create entity card for the user
            user_card = EntityCard(
                id=str(uuid.uuid4()),
                entity_name=full_name,
                entity_type='Person',
                summary=f"{full_name} is the user of this AI assistant (pronouns: {pronoun_subjective}/{pronoun_objective}).",
                key_facts=json.dumps([
                    f"Name: {full_name}",
                    f"Pronouns: {pronoun_subjective}/{pronoun_objective}",
                    f"Birthdate: {user_data.get('birthdate', 'Not specified')}",
                    f"Job: {user_data.get('job', 'Not specified')}"
                ]),
                relationships=json.dumps([]),
                aliases=json.dumps([full_name, user_data['first_name'], user_data.get('preferred_name', full_name)]),
                card_metadata=json.dumps({}),
                is_active=True,
                usage_count=0
            )
            session_db.add(user_card)
            
            # Create entity cards for important people
            important_people = data.get('important_people', [])
            for person in important_people:
                if person.get('name'):
                    summary = f"{person['name']} is {full_name}'s {person.get('relationship', 'acquaintance')}."
                    
                    key_facts = [
                        f"Name: {person['name']}",
                        f"Relationship: {person.get('relationship', 'Known to user')}"
                    ]
                    if person.get('birthdate'):
                        key_facts.append(f"Birthdate: {person['birthdate']}")
                    
                    person_card = EntityCard(
                        id=str(uuid.uuid4()),
                        entity_name=person['name'],
                        entity_type='Person',
                        summary=summary,
                        key_facts=json.dumps(key_facts),
                        relationships=json.dumps([f"{person.get('relationship', 'Known to')} {full_name}"]),
                        aliases=json.dumps([person['name']]),
                        card_metadata=json.dumps({}),
                        is_active=True,
                        usage_count=0
                    )
                    session_db.add(person_card)
            
            session_db.commit()
        except Exception as e:
            session_db.rollback()
            raise e
        finally:
            session_db.close()
        
        # Mark setup as complete in session
        session['setup_complete'] = True
        
        return jsonify({
            'success': True,
            'message': 'Setup completed successfully!',
            'redirect': url_for('chat_bot.chat_bot')
        })
        
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@setup_bp.route('/api/setup/reset', methods=['POST'])
def reset_setup():
    """Reset setup (for testing/reconfiguration)"""
    try:
        resources_dir = Path(__file__).resolve().parents[2] / 'resources'
        
        # Delete resource files
        files_to_delete = [
            'resource_user_data.json',
            'resource_assistant_personality_data.json',
            'resource_relationship_config.json',
            'resource_chat_guidelines_data.json'
        ]
        
        for filename in files_to_delete:
            file_path = resources_dir / filename
            if file_path.exists():
                file_path.unlink()
        
        # Clear session
        session.pop('setup_complete', None)
        
        return jsonify({
            'success': True,
            'message': 'Setup reset successfully'
        })
        
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

